# Generated by Django 2.1.7 on 2019-06-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['create_date'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
