# Generated by Django 2.1.7 on 2019-06-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190625_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_drafe',
            field=models.BooleanField(default=True),
        ),
    ]
